
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 72;
const int acc_off_y = -8;
const int acc_off_z = 211;
const float acc_scale_x = 15827.435944;
const float acc_scale_y = 16533.974047;
const float acc_scale_z = 16841.679423;

const int magn_off_x = 56;
const int magn_off_y = -73;
const int magn_off_z = -145;
const float magn_scale_x = 753.324584;
const float magn_scale_y = 742.324931;
const float magn_scale_z = 632.931308;
